<a href="https://colab.research.google.com/github/aakanshatomar3906-source/PYTHON-BEGINNER-PROJECTS/blob/main/Pytorch_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# pytorch pahle se install hota hai google colab mein
import torch
print(torch.__version__)


2.10.0+cpu


In [ ]:
if torch.cuda.is_available():
  print("GPU is available")
  print(f"Using GPU:{torch.cuda.get_device_name(0)}")
else:
  print("GPU is not available.Using CPU ")

GPU is not available.Using CPU 


CREATING A TENSOR



In [ ]:
# CHECK EMPTY
torch.empty(2,3)

tensor([[3.1639e+33, 4.4746e-41, 3.4566e-04],
        [0.0000e+00, 4.4842e-44, 0.0000e+00]])

In [ ]:
# CHECK TYPE
type(torch.empty(2,3))

torch.Tensor

In [ ]:
# USING ZEROS
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
# USING ONES
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
# USING RAND
torch.rand(2,3)

tensor([[0.1828, 0.8298, 0.1047],
        [0.3387, 0.8089, 0.3791]])

In [ ]:
# USING SEED
# MANUAL_SEED
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
# USING TENSOR
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
# OTHER WAYS:-

# arange
print("using arange ->",torch.arange(0,10))

# using linspace
print("using linspace ->", torch.linspace(0,10,10))

# using eye
print("using eye ->" , torch.eye(5))

# using full
print("using full ->", torch.full((3,3),5))

using arange -> tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


TENSOR SHAPES


In [ ]:
x=torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
x.shape

torch.Size([2, 3])

In [ ]:
torch.empty_like(x) # iske tarike ka matlab usi shape ka ek new tensor form ho gya

tensor([[433791697012, 493921239150, 489626271855],
        [390842023976, 210453397595, 214748364844]])

In [ ]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [ ]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [ ]:
torch.rand_like(x)
# ? Reason => rand jo function hai yeh float generate karta hai.

NotImplementedError: "check_uniform_bounds" not implemented for 'Long'

TENSOR DATA TYPES


In [ ]:
# Find data type
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
x.dtype

torch.int64

In [ ]:
# assign data type
torch.tensor([1.0,2.0,3.0],dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [ ]:
torch.tensor([1,2,3],dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [ ]:
# using to()
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [ ]:
torch.rand_like(x,dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

MATHEMATICAL OPERATIONS

1. SCALAR OPERATION

In [ ]:
# addition
x+2

# subtraction
x-2

# multiplication
x*3

# division
x/3

# int division
(x*100)//3

# mod
((x*100)//3)%2

# power
x**2

tensor([[ 1,  4,  9],
        [16, 25, 36]])

2. ELEMENT WISE OPERATION

In [ ]:
a=torch.rand(2,3)
b=torch.rand(2,3)
print(a)
print(b)

tensor([[0.7118, 0.7876, 0.4183],
        [0.9014, 0.9969, 0.7565]])
tensor([[0.2239, 0.3023, 0.1784],
        [0.8238, 0.5557, 0.9770]])


In [ ]:
# add
a+b
# sub
a-b
# multiply
a*b
# division
a/b
# power
a**b
# mod
a%b

tensor([[0.0401, 0.1829, 0.0615],
        [0.0776, 0.4411, 0.7565]])

In [ ]:
c=torch.tensor([1,-2,3,-4])
c

tensor([ 1, -2,  3, -4])

In [ ]:
# abs
torch.abs(c)

tensor([1, 2, 3, 4])

In [ ]:
# negative
torch.neg(c)

tensor([-1,  2, -3,  4])

In [ ]:
d=torch.tensor([1.9,2.3,3.7,4.4])
d

tensor([1.9000, 2.3000, 3.7000, 4.4000])

In [ ]:
# round
torch.round(d)

tensor([2., 2., 4., 4.])

In [ ]:
# ceil
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [ ]:
# floor
torch.floor(d)

tensor([1., 2., 3., 4.])

In [ ]:
# clamp
torch.clamp(d,min=2,max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

REDUCTION OPERATION

In [ ]:
e=torch.randint(size=(2,3),low=0,high=10)
e

tensor([[7, 6, 0],
        [1, 6, 2]])

In [ ]:
# sum
torch.sum(e)

# sum along columns
torch.sum(e,0)
torch.sum(e,dim=0)

# sum along rows
torch.sum(e,dim=1)

tensor([13,  9])

In [ ]:
# mean
#torch.mean(e)  # error=> only work with float point number.
f=torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)
torch.mean(f)

# mean along column
torch.mean(f,dim=0)

tensor([3.5000, 0.0000, 9.0000])

In [ ]:
# median
torch.median(f)

tensor(3.)

In [ ]:
# max and min
torch.max(f)
torch.min(f)

tensor(0.)

In [ ]:
# product
torch.prod(e)

tensor(0)

In [ ]:
# standard deviation
torch.std(f)

tensor(4.0702)

In [ ]:
# variance
torch.var(f)

tensor(16.5667)

In [ ]:
# argmax
torch.argmax(e)

tensor(0)

In [ ]:
# argmin
torch.argmin(e)

tensor(2)

MATRIX OPERATIONS:-

In [ ]:
m=torch.randint(size=(2,3),low=0,high=10)
n=torch.randint(size=(3,2),low=0,high=10)
print(m)
print(n)

tensor([[0, 0, 5],
        [9, 6, 0]])
tensor([[9, 7],
        [3, 0],
        [3, 0]])


In [ ]:
# matrix multiplication
torch.matmul(m,n)

tensor([[15,  0],
        [99, 63]])

In [ ]:
vector1=torch.tensor([1,2])
vector2=torch.tensor([3,4])

# dot product
torch.dot(vector1,vector2)

tensor(11)

In [ ]:
# transpose
torch.transpose(m,0,1)

tensor([[0, 9],
        [0, 6],
        [5, 0]])

In [ ]:
h=torch.randint(size=(3,3),low=0,high=10,dtype=torch.float32)
h

tensor([[8., 6., 0.],
        [9., 9., 5.],
        [8., 0., 2.]])

In [ ]:
# determinant
torch.det(h)

tensor(276.)

In [ ]:
# inverse
torch.inverse(h)

tensor([[ 0.0652, -0.0435,  0.1087],
        [ 0.0797,  0.0580, -0.1449],
        [-0.2609,  0.1739,  0.0652]])

5. COMPARISON OPERATIONS

In [ ]:
i=torch.randint(size=(2,3),low=0,high=10)
j=torch.randint(size=(2,3),low=0,high=10)

print(i)
print(j)

tensor([[9, 7, 4],
        [3, 6, 8]])
tensor([[8, 0, 8],
        [9, 0, 3]])


In [ ]:
# greater than
i>j

# less than
i<j

# equal to
i==j

# not equal to
i!=j

# greater than equal to
i>=j

tensor([[ True,  True, False],
        [False,  True,  True]])

6. SPECIAL FUNCTIONS

In [ ]:
k=torch.randint(size=(2,3),low=0,high=10)
k

tensor([[9, 0, 9],
        [2, 2, 2]])

In [ ]:
# log
torch.log(k)

tensor([[2.1972,   -inf, 2.1972],
        [0.6931, 0.6931, 0.6931]])

In [ ]:
# expo
torch.exp(k)

tensor([[8.1031e+03, 1.0000e+00, 8.1031e+03],
        [7.3891e+00, 7.3891e+00, 7.3891e+00]])

In [ ]:
# sqrt
torch.sqrt(k)

tensor([[3.0000, 0.0000, 3.0000],
        [1.4142, 1.4142, 1.4142]])

In [ ]:
# sigmoid
torch.sigmoid(k)

tensor([[0.9999, 0.5000, 0.9999],
        [0.8808, 0.8808, 0.8808]])

In [ ]:
# softmax
k=torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)
torch.softmax(k,dim=0)

tensor([[8.8080e-01, 3.3535e-04, 9.5257e-01],
        [1.1920e-01, 9.9966e-01, 4.7426e-02]])

In [ ]:
# relu
torch.relu(k)

tensor([[7., 0., 6.],
        [5., 8., 3.]])

INPLACE OPERATIONS

In [ ]:
M=torch.rand(2,3)
N=torch.rand(2,3)

print(M)
print(N)

tensor([[0.5191, 0.5730, 0.7400],
        [0.4078, 0.7672, 0.3576]])
tensor([[0.9581, 0.2331, 0.1453],
        [0.9152, 0.6881, 0.5093]])


In [ ]:
M+N

tensor([[1.4773, 0.8060, 0.8854],
        [1.3230, 1.4553, 0.8668]])

In [ ]:
M.add_(N)

tensor([[1.4773, 0.8060, 0.8854],
        [1.3230, 1.4553, 0.8668]])

In [ ]:
torch.relu(M)

tensor([[1.4773, 0.8060, 0.8854],
        [1.3230, 1.4553, 0.8668]])

In [ ]:
M.relu_()

tensor([[1.4773, 0.8060, 0.8854],
        [1.3230, 1.4553, 0.8668]])

COPYING A TENSOR

In [ ]:
a=torch.rand(2,3)
a

tensor([[0.4013, 0.8340, 0.2208],
        [0.5284, 0.8328, 0.9514]])

In [ ]:
b=a
b

tensor([[0.4013, 0.8340, 0.2208],
        [0.5284, 0.8328, 0.9514]])

In [ ]:
a[0][0]=0
a

tensor([[0.0000, 0.8340, 0.2208],
        [0.5284, 0.8328, 0.9514]])

In [ ]:
b
# not desirable and yeh assignment operator kar deta hai.

tensor([[0.0000, 0.8340, 0.2208],
        [0.5284, 0.8328, 0.9514]])

In [ ]:
id(a)

135442584422112

In [ ]:
id(b)

135442584422112

In [ ]:
b=a.clone()
b

tensor([[0.0000, 0.8340, 0.2208],
        [0.5284, 0.8328, 0.9514]])

In [ ]:
a[0][0]=10
a

tensor([[10.0000,  0.8340,  0.2208],
        [ 0.5284,  0.8328,  0.9514]])

In [ ]:
b

tensor([[0.0000, 0.8340, 0.2208],
        [0.5284, 0.8328, 0.9514]])

TENSOR OPERATIONS ON GPU

In [ ]:
torch.cuda.is_available()

False

In [ ]:
device=torch.device('cuda')

In [ ]:
# creating a new tensor on GPU
torch.rand((2,3),device=device)

AssertionError: Torch not compiled with CUDA enabled

In [ ]:
# moving an existing tensor to GPU
a=torch.rand(2,3)
a

tensor([[0.9913, 0.9782, 0.9326],
        [0.8134, 0.6800, 0.7575]])

In [ ]:
a.to(device)

RESHAPING TENSORS

In [ ]:
a=torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
# reshape
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [ ]:
# flatten
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
b=torch.rand(2,3,4)
b

tensor([[[0.4314, 0.0459, 0.0311, 0.6437],
         [0.9399, 0.3294, 0.8685, 0.8696],
         [0.9000, 0.7477, 0.6764, 0.6843]],

        [[0.2676, 0.8749, 0.9002, 0.3411],
         [0.5850, 0.6940, 0.9953, 0.3973],
         [0.2365, 0.2466, 0.2913, 0.1603]]])

In [ ]:
# permute
b.permute(2,0,1)
b.permute(2,0,1).shape

torch.Size([4, 2, 3])

In [3]:
# unsqueeze
c=torch.rand(226,226,3)  # typical image size
c.unsqueeze(2).shape

torch.Size([226, 226, 1, 3])

In [4]:
# squeeze
d=torch.rand(1,20)
d.squeeze(0)
d.squeeze(0).shape

torch.Size([20])

  NumPy and PyTorch

In [5]:
import numpy as np

In [6]:
a=torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [7]:
b=a.numpy()

In [8]:
type(b)

numpy.ndarray

In [9]:
c=np.array([1,2,3])
c

array([1, 2, 3])

In [10]:
torch.from_numpy(c)

tensor([1, 2, 3])